SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - silverstripe-cms-theme/dist/main.css
  extensions:
    - RyanPotter\SilverStripeCMSTheme\Extensions\LeftAndMainExtension
    - RyanPotter\SilverStripeCMSTheme\Extensions\GroupedCmsMenu

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - RyanPotter\SilverStripeCMSTheme\Extensions\SiteConfigExtension
