LeftAndMain:
  extra_requirements_css:
    - https://fonts.googleapis.com/css?family=Roboto:400,700
    - silverstripe-branding/css/main.min.css

SiteConfig:
  extensions:
    - CMSBrandingSiteConfigExtension